### ISSUE TITLE
Getting SetCommError when started again after closing the port.

### ISSUE THREAD

**Issue by MANOJKUMAR26** [FengChendian/serial_port_win32#38]
Hi Team,
I am trying to **read serial data through USB for flutter windows desktop application**. The data gets read the first time properly but when I stop the port and start the reading again, I am getting setCommState error. 
I am using : **serial_port_win32: ^1.3.0**

Below is the code I am using to open the port and read the data and close the port.

late SerialPort port;
 void _getPortsAndClose() {
    port.close();
    showToast(
      'Readings stopped successfully',
      duration: Duration(seconds: 3),
      position: const ToastPosition(align: Alignment.topRight),
      backgroundColor: Colors.green
    );
  }
  
  void _getPortsAndOpen(Device selectedDevice) {
    final List<PortInfo> portInfoLists = SerialPort.getPortsWithFullMessages();
    ports = SerialPort.getAvailablePorts();
    String datacopy = '';
    print(portInfoLists);
    print(ports);
    if (ports.isNotEmpty) {

      port = SerialPort(selectedDevice.portName,
          openNow: false,BaudRate:9600, ReadIntervalTimeout: 1, ReadTotalTimeoutConstant: 2);
      port.open();
      
      String incomingData = '';
      String completeData = '';

      // while (port.isOpened) {
      // incomingData = '';
      port.readBytesOnListen(8, (value) {
        print('check vlaue ${utf8.decode(value)}');
      // if (utf8.decode(value) != '+' && utf8.decode(value) != ',') {
      incomingData += utf8.decode(value);
      print('check incoming data ${incomingData.length}');
      if(incomingData.length > 50) {
          String trimmedData = incomingData.substring(35);
          incomingData = trimmedData;
      }
      List<String> parts = incomingData.split(',');
      final regex = RegExp(r'\+\d+(?:\.\d+)?'); // Matches numbers optionally followed by a decimal point
      List<double> extractedValues = [];
      for (var part in parts) {
        final match = regex.matchAsPrefix(part);
        if (match != null) {
          // Extract the captured group (the number) and convert to double
          extractedValues.add(double.parse(match.group(0)!.substring(1))); // Remove leading "+"
        }
      }

      if (extractedValues.length >= 2) {
        completeData = extractedValues[extractedValues.length - 2].toString();
      }
      
      setState(() {data = completeData;});
      }
      );
      }
      
      Can you help me resolve this issue please?
      Below are the attempts I did to fix the issue:
      1) Tries to set stop bits to 0 and 1, didn't help.
      2) Tried giving delay before stopping the port so that if there is any queue it can complete but that also didn't help.

**Comment by FengChendian** [comment]
Did you re-create a same device name SerialPort? It shoude be single-instance mode.

**Comment by MANOJKUMAR26** [comment]
Actually in my scenario, the same device can be connected to different COM ports, Now I tried creating singleton class for serial port and called the same in the method like below:
class SerialPortSingleton {
  static final SerialPortSingleton _instance = SerialPortSingleton._internal();
  SerialPort? port;

  factory SerialPortSingleton() {
    return _instance;
  }

  SerialPortSingleton._internal();

  void initialize(String portName) {
    if (port == null) {
      port = SerialPort(portName, openNow: false, BaudRate: 9600, ReadIntervalTimeout: 1, ReadTotalTimeoutConstant: 2);
    }
  }

  void openPort() {
    if (port != null && !port!.isOpened) {
      port!.open();
    }
  }

  void closePort() {
    if (port != null && port!.isOpened) {
      port!.close();
    }
  }
}

**And in the method I am calling as below:**
if (ports.isNotEmpty) {
      SerialPortSingleton().initialize(selectedDevice.portName);
      SerialPortSingleton().openPort();
      print(SerialPortSingleton().port?.isOpened);
      
**For closing port:**
      SerialPortSingleton().port?.close();
      
But like I said first time when I started the reading it showed perfectly. After stopping the port and starting again, I am still getting the same error as below:
flutter: [Port Name: COM5, FriendlyName: USB-SERIAL CH340 (COM5)]        
flutter: [COM5]
**Another exception was thrown: Exception: SetCommState error**
flutter: [Port Name: COM5, FriendlyName: USB-SERIAL CH340 (COM5)]        
flutter: [COM5]
**Another exception was thrown: Exception: Open port failed, error is 5**

I don't have much info on these errors.

**Comment by FengChendian** [comment]
> Hello @FengChendian , Thanks for your response.
> 
> Actually in my scenario, the same device can be connected to different COM ports, Now I tried creating singleton class for serial port and called the same in the method like below: class SerialPortSingleton { static final SerialPortSingleton _instance = SerialPortSingleton._internal(); SerialPort? port;
> 
> factory SerialPortSingleton() { return _instance; }
> 
> SerialPortSingleton._internal();
> 
> void initialize(String portName) { if (port == null) { port = SerialPort(portName, openNow: false, BaudRate: 9600, ReadIntervalTimeout: 1, ReadTotalTimeoutConstant: 2); } }
> 
> void openPort() { if (port != null && !port!.isOpened) { port!.open(); } }
> 
> void closePort() { if (port != null && port!.isOpened) { port!.close(); } } }
> 
> **And in the method I am calling as below:** if (ports.isNotEmpty) { SerialPortSingleton().initialize(selectedDevice.portName); SerialPortSingleton().openPort(); print(SerialPortSingleton().port?.isOpened);
> 
> **For closing port:** SerialPortSingleton().port?.close();
> 
> But like I said first time when I started the reading it showed perfectly. After stopping the port and starting again, I am still getting the same error as below: flutter: [Port Name: COM5, FriendlyName: USB-SERIAL CH340 (COM5)] flutter: [COM5] **Another exception was thrown: Exception: SetCommState error** flutter: [Port Name: COM5, FriendlyName: USB-SERIAL CH340 (COM5)] flutter: [COM5] **Another exception was thrown: Exception: Open port failed, error is 5**
> 
> I don't have much info on these errors.

Do you use port.close before you re-open it? Error code 5 means that **Access is denied. ** It happened when your serial port is occupied (not closed in last instance).

![image](https://github.com/user-attachments/assets/ddc88029-668e-40b0-88d4-55607082c9ff)

**Comment by MANOJKUMAR26** [comment]
Hello @FengChendian ,
I have made sure (checked during debug mode also) to close the port before I try to re-open but still I am getting this error. 
Like you said If I remove the usb plug and insert the plug again, it works but keeping it inserted always and trying to close and open the port programmatically is causing the problem. Can you help me to fix this issue please?

**Comment by FengChendian** [comment]
I tested it. And I think it's due to the basic dependency ( `win32` package) is too older. I will try to update it to the latest version. You can try it again.

**Comment by FengChendian** [comment]
In example folder, you can see
```dart
  void _send() async {
    if (!port.isOpened) {
      port.open();
    }
    port.writeBytesFromString("AT", includeZeroTerminator: false);
    print(await port.readBytesUntil(Uint8List.fromList("T".codeUnits)));
    port.close();
  }
```

I use this code to test close and re-open. And it worked perfectly with latest `win32 5.7.2`. But not worked on `win32 5.0.5`.

**Comment by MANOJKUMAR26** [comment]
Hello @FengChendian ,
Even after upgrading to 1.4.2 version, I am facing the same issue.
First time it opens the ports and reads properly. During the call of **port.close** function I can see in the debug mode that isOpened is changing to false.
But still second time when i tried to open and read the port, getting **"_Exception (Exception: SetCommState error)"**

The below is where exactly I am facing the issue:
![image](https://github.com/user-attachments/assets/d2aa1aea-bff7-40f8-8360-f380a4bec735)

Can you please help me out with this?

**Comment by FengChendian** [comment]
> Hello @FengChendian , Even after upgrading to 1.4.2 version, I am facing the same issue. First time it opens the ports and reads properly. During the call of **port.close** function I can see in the debug mode that isOpened is changing to false. But still second time when i tried to open and read the port, getting **"_Exception (Exception: SetCommState error)"**
> 
> The below is where exactly I am facing the issue: ![image](https://private-user-images.githubusercontent.com/32367884/382555722-d2aa1aea-bff7-40f8-8360-f380a4bec735.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA3MzQxMjksIm5iZiI6MTczMDczMzgyOSwicGF0aCI6Ii8zMjM2Nzg4NC8zODI1NTU3MjItZDJhYTFhZWEtYmZmNy00MGY4LTgzNjAtZjM4MGE0YmVjNzM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA0VDE1MjM0OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjMjA5MjQyNDdmODY5YWMyNWFmM2I3YjIxYmQyNmZjNzEzYzQ2NjBkMTQzNzgxNzA3ODFiMDI3MTkxY2E5MzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kfZbVpDgyA3myCPLPmQBiKN-Rdl_yXC1q7hCn2magWM)
> 
> Can you please help me out with this?

Um... It's really strange. 

I see your readData in your call stack. Maybe `readOnListen` causes `setCommState` error in some specific plaform?

- Can you disable all read/write functions and re-test it? 

- Or please give me a mini whole example project which can reproduce the bug. Although maybe it doesn't occur on my pc.

**Comment by MANOJKUMAR26** [comment]
Hello @FengChendian ,
Below is my flutter and dart version - 

- Flutter 3.27.0-1.0.pre.327 • channel master • https://github.com/flutter/flutter.git
- Framework • revision b18d34c574 (8 days ago) • 2024-10-31 22:53:17 -0400
- Engine • revision cd46383cd5
- Tools • Dart 3.7.0 (build 3.7.0-88.0.dev) • DevTools 2.40.1
- Windows version - 11

Sharing you the example code repository which is causing the error.
https://github.com/[MANOJKUMAR26/serial_win_32_sample_project](https://github.com/MANOJKUMAR26/serial_win_32_sample_project/tree/test)/tree/test)

Can you please check and suggest if I am going wrong somewhere.

**Comment by FengChendian** [comment]
@MANOJKUMAR26 
In your code, bug can be reproduced.

******
Please **remove**  `ports = SerialPort.getAvailablePorts();` Then the bug shoulde be fixed.
******

I don't really know why error occurs when you use both `getAvailablePorts` and `open` in gesture.

**Comment by FengChendian** [comment]
The `getAvailablePorts` bug should be fixed in version 2.1.1. Thanks for **@halildurmus**.  

You can use version 2.1.1. However, in version 2.x.x, you should read as `port.readBytes(18, timeout: Duration(milliseconds: 10))..then((onValue) => print(onValue))`. It's a little different from version 1.x for the dart-newer friendly API.

Example:
```dart
print(await port.readBytesUntil(Uint8List.fromList("T".codeUnits))); /// '\0' is not included
/// or
var read = port.readBytes(18, timeout: Duration(milliseconds: 10))..then((onValue) => print(onValue));
var result = await read;
print(result);
/// or
var fixedBytesRead = port.readFixedSizeBytes(2)..then((onValue) => print(onValue));
await fixedBytesRead;
/// see more in small example
```

**Comment by MANOJKUMAR26** [comment]
Hello @FengChendian ,
I am using the physical device (USB Serial port) to test the code.
I upgraded the library version to **serial_port_win32: ^2.1.3** and tried using the above code which you shared removing singleton code and I see the error still exist and this time I am not able to open the port from the first time only.
![image](https://github.com/user-attachments/assets/e2fa0500-ddf1-4cd6-bbb9-51ce7ed4e52a)

**Comment by FengChendian** [comment]
@MANOJKUMAR26 

- Do not use hot restart if you have tried to open port. Hot restart doesn't' restart win32 API. So handler will be `INVALID_HANDLE_VALUE` but there is a valid handle (opened port) which you can't fetch.

**Comment by MANOJKUMAR26** [comment]
Hello @FengChendian ,
Now I can open and close the port but when I open the port every time, I am getting below attached error.
I am not able to read the data after I open the port, not sure if this is because of the below attached error.
Previously readBytesOnListen function used to show the correct reading from the same device but now with this new read functions (tried all 3 read function) I am getting just array of zeros.
![image](https://github.com/user-attachments/assets/bb01f3fd-b4d9-45cf-9db2-4a84d1d2caf0)
![image](https://github.com/user-attachments/assets/2128331a-bd5e-46e9-bab2-6d16787ab59d)
Can you please suggest

**Comment by FengChendian** [comment]
It's a really weird bug……

So,
- In version 1.x, you cannot open with `SetCommState` Error code `0`, but you can read right thing.
- In version 2.x,`SetCommState` reports error code `31`

---
# Some questions
@MANOJKUMAR26 
- What's your ch340 driver version? My version is `3.8.2023.2` The test for ch340 local loopback in `example/main.dart` can work on my pc. You can see it in COM Port properties --> Driver.
- You need set proper `BandRate` if you communicate with other devices. I see your original code is 9600. But now you use default '115200'.

**Comment by MANOJKUMAR26** [comment]
Sharing you the driver version for the first error:
![image](https://github.com/user-attachments/assets/b01adf83-8e54-46a6-ac68-5d6433527e4e)
![image](https://github.com/user-attachments/assets/93781184-9f05-47e3-83d0-73faf7f56393)

Also Sorry, As you suggested It was my mistake on updating the baud rate. I have updated it to 9600 and tried to use readBytes function but I am getting only one value. Actually the device value keeps changing and all the changing of numbers should be visible on screen but It is sending only one initial value.
I tried using **print(await serialSingle!.readBytesUntil(Uint8List.fromList("T".codeUnits)));** function also but I am not getting any data using this function and when I close the port I am getting below error for readBytesUntil Function.
![image](https://github.com/user-attachments/assets/0bba8aec-6253-4424-932c-0e44b2bd5e62)

**Comment by FengChendian** [comment]
@MANOJKUMAR26 
1. You use `readBytes` once, so it read once. It should be true behaviour. If you want to read loop, you can use code like:
```dart
for (int i=0; i < 100; i++) {
var a = await readBytes();
/// some things
}
```

It is a basic loop read. Also, you can use stream like:
```dart
Stream<Uint8List> process() async* {
  for (int i=0; i < 100; i++) {
  var a = await readBytes();
  yield a;
  }
}
```

In version 1.x, you can use `readOnListen` to loop read. But it can't be directly controlled by users. So, I remove it in 2.x.


2. I thinks this is a reasonable exception. You use `readBytesUntil` to read something, but return conditions is not satisfied for some reasons. Your read is still not completed. If you close the port, you will still read after close port (Maybe I should add some warning in close port and stop read). You need to ensure that all I/O function is done when you close it.
